version: '3.8'
service:
db:
  image: postgres:latest
  container_name: bd
  restart: always
  enviroment:
  - POSTGRES_HOST= 0.0.0.0
  - POSTGRES_USER= postgres
  - POSTGRES_PASSWORD= Gta989jm
  - POSTGRES_DB= task_db
  ports:
  - 5432:5432
  
  app: 
    build: .
    container_name: BackEnd
    restart: always 
    enviroment:
     DATABASE_URL: "postgresql://postgres:Gta989jm@localhost:5432/task_db?schema=public"
     ports:
     - "3000:3000"
    depends_on:
    - db
